#!/usr/bin/env awk -f
function usage(msg) {
	print msg >"/dev/stderr"
	print "usage: " ARGV[0] " {table} [files]" >"/dev/stderr"
	exit 1
}
BEGIN {
	fileno=0
	if(ARGC == 1){
		usage("Lookup file is required.")
	}
	if(ARGC == 2){
		ARGV[ARGC] = "/dev/stdin"
		ARGC++
	}
}
fileno == 0 {
	tab[NR-1] = $1;
	for(n = 1; n <= NF; n++){
		tab[$n] = NR-1
	}
}
ENDFILE { fileno++ }
fileno != 0 {
	for(n = 1; n <= NF; n++){
		if(tab[$n] != "")
			$n = tab[$n]
	}
	print
}
